### ISSUE TITLE
support more spec-compliant promise implementations

### ISSUE THREAD

**Issue by jonathanong** [normalize/native-or-bluebird#1]
don't see a need to only rely on bluebird

**Comment by dougwilson** [comment]
I like bluebird and the author's responsiveness, and so it would be awesome if bluebird had a way to say "I need a Promise that is the minimal required by spec" and then we could simply export that constructor here.

**Comment by ruimarinho** [comment]
Agreed, the amount of knowledge that bluebird's author brings to this topic is overwhelming. I concur that the it is not strictly ES6-compliant, but if we educate the community to stick with ES6 promise methods, then the switch will be made much simpler.

**Comment by dougwilson** [comment]
Maybe https://github.com/jakearchibald/es6-promise ?

**Comment by ruimarinho** [comment]
@dougwilson, es6-promise is already a subset of rsvp.js, so ideally bluebird would also expose a minimal ES6-compliant API too. However, given the author's position on native promises (slow and limited), I'm pretty sure that is not going to happen.

**Comment by ruimarinho** [comment]
Seems like someone has made exactly that - [bluebird-es6](https://www.npmjs.com/bluebird-es6), a custom built version of bluebird with only the ES6 methods and `promisify`.

**Comment by lookfirst** [comment]
Or just use Babel and start writing ES6 Promise code today. http://babeljs.io/docs/learn-es6/#promises

(Note: it uses the core.js implementation of Promises.)

The thing that scares me about this project is that bluebird is * in the package.json. So, you either have * or you have it pinned to some major version with ^. If you depend on this project, then you will always have the issue of being tied to whatever version this project decides to depend on, which right now could be anything.

**Comment by epoberezkin** [comment]
http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird
